### PR TITLE
feat(sdl): add SDL_HIGHDPI define to allow high DPI render

### PR DESCRIPTION
**Pull request by slightc**
#309

### CODE REVIEW

**Comment by kisvegabor** [comment]
What does it change in the practice?

**Comment by kisvegabor** [comment]
The [docs](https://wiki.libsdl.org/SDL2/SDL_WindowFlags) says
> window should be created in high-DPI mode if supported (>= SDL 2.0.1)

So it won't be used if not supported. Therefore I wonder if we can add it unconditionally.

**Comment by slightc** [comment]
I think that should be a config field, it is up to the user to decide on their own

**Comment by ITotalJustice** [comment]
> The [docs](https://wiki.libsdl.org/SDL2/SDL_WindowFlags) says
> 
> > window should be created in high-DPI mode if supported (>= SDL 2.0.1)
> 
> So it won't be used if not supported. Therefore I wonder if we can add it unconditionally.

you mean like?
```c
#if defined(SDL_HIGHDPI) && SDL_HIGHDPI &&  SDL_VERSION_ATLEAST(2, 0, 1)
flag |= SDL_WINDOW_ALLOW_HIGHDPI
#endif
```
to https://github.com/lvgl/lv_drivers/blob/0091dc612facc94dce1061a9b78d641c77f1791a/sdl/sdl.c#L336

**Comment by slightc** [comment]
I think use SDL_HIGHDPI macro definition check, that should be defined by those in need, no need for additional version checking (want to keep simplicity).

**Comment by slightc** [comment]
emm, that like this?
``` c
#ifndef SDL_HIGHDPI
# define SDL_HIGHDPI  SDL_VERSION_ATLEAST(2, 0, 1)
#endif

#if SDL_HIGHDPI
    flag |= SDL_WINDOW_ALLOW_HIGHDPI;
#endif
```

**Comment by kisvegabor** [comment]
Or just:
```c
#if SDL_VERSION_ATLEAST(2, 0, 1)
    flag |= SDL_WINDOW_ALLOW_HIGHDPI;
#endif
```

**Comment by slightc** [comment]
@kisvegabor I'm update it, I think that may best can be force enable/disable by developer, so still use the `SDL_HIGHDPI`, this PR maybe OK?

**Pull request merged**
