### PR TITLE
fbdev: add functions for getting screen resolution

### PR DESCRIPTION
**Pull request by DolphinChips**
This can be used for creating generic app where you don't know what screen resolution user will have.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Thanks!

**Comment by DolphinChips** [comment]
Marking as WIP, would like to make it more consistent with PR above.

**Comment by DolphinChips** [comment]
> 
> 
> Marking as WIP, would like to make it more consistent with PR above.

Done.

**Comment by kisvegabor** [comment]
Great! Can I merge it now?

**Pull request merged**
