### PR TITLE
GPU Supported SDL Backend

### PR DESCRIPTION
**Pull request by mariotaku**

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

It seems this PR was forgotten.

 I resolved the conflicts and marked this PR as ready. Is it ready to merge?

**Comment by mariotaku** [comment]
The merge looks good to me!

**Comment by kisvegabor** [comment]
I've just tested it it still crashes with this initialization:
```c
  sdl_disp_drv_init(&disp_drv, SDL_HOR_RES, SDL_VER_RES); /*Basic initialization*/
  lv_disp_t * disp = lv_disp_drv_register(&disp_drv);
```

```
WARN: 

Assertion failure at lv_draw_sdl_rect_bg_frag_obtain (../lvgl/src/draw/sdl/lv_draw_sdl_rect.c:156), triggered 1 time:
  'texture'
```

Do you what can be still missing?

**Comment by mariotaku** [comment]
@kisvegabor I think this is because lvgl/lvgl#3167. I have created another PR https://github.com/lvgl/lvgl/pull/3280 to revert the change, after the change, sample app will run.

**Comment by kisvegabor** [comment]
Thank you, it's working now.

But there are some minor issues :slightly_frowning_face: 

The widgets demo looks like this: 
image

Instead of:
image


So
- All texts are black (some should be white)
- No images

**Comment by mariotaku** [comment]
Is this on Linux? On Windows (with MinGW) it works fine. My code is based on `lv_sim_vscode_sdl`.

**Comment by kisvegabor** [comment]
Yes, I'm on Linux. Do you use the latest LVGL?

**Comment by mariotaku** [comment]
I think they are quite new.

```
 2d7f3f619b447c97f2af825b82a75611124f5e04 lv_drivers (v8.1.0-16-g2d7f3f6)
 6a179e2c8e67afbcd30fbd7a1f6134799e602828 lv_examples (v7.11.0-120-g6a179e2)
 9997fb00aa60b4478c76fa8387a74ca5b3c595b2 lvgl (v8.2.0-173-g9997fb00a)
```

**Pull request merged**
