### PR TITLE
feat(indev): refactor evdev to allow multiple devices

### PR DESCRIPTION
**Pull request by niklasf**
~~New usage example: [...]~~

Backported improvements from v9 in a compatible way.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Thank you! I can merge it now, but could you port it v9 as well and send a PR for LVGL master?

**Comment by niklasf** [comment]
Sure. Started the port here: https://github.com/lvgl/lvgl/pull/4672

**Comment by kisvegabor** [comment]
Thank you! :pray:

**Comment by kisvegabor** [comment]
The PR is still in Draft state. Are there anything else to add?

**Comment by niklasf** [comment]
Good to go. Just wanted to test with real hardware before marking as ready.

**Comment by kisvegabor** [comment]
Cool, merged, thank you! :blush:

**Pull request merged**
