### PR TITLE
fix wayland physical keyboard issue

### PR DESCRIPTION
**Pull request by pyway**
for lvgl-v8.3.x, lv_indev_set_group added for the physical keyboard working on ubuntu 22.04 / wayland.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi, 

the `master` branch of `lv_drivers` should be compatible with LVGL's `master` branch in which we have `lv_malloc` and `lv_free` instead of `lv_mem_alloc` and `lv_mem_free`.

Could you rebase this on `release_v8.3` branch and cherry pick the changes to `master`?

**Comment by pyway** [comment]
Hi,
  there seems no lv_malloc/free with  lvgl 8.3.4 & lv_drivers-master which i downloaded, but lvgl-master does.
 maybe need macro definitions lv_malloc/free at least for lvgl-8.3.4.

> Hi,
> 
> the `master` branch of `lv_drivers` should be compatible with LVGL's `master` branch in which we have `lv_malloc` and `lv_free` instead of `lv_mem_alloc` and `lv_mem_free`.
> 
> Could you rebase this on `release_v8.3` branch and cherry pick the changes to `master`?

**Comment by pyway** [comment]
@kisvegabor rebase on the lvgl master, updated. plz check if this is a real issue, or is there other solving? 
else, with lvgl-master, the widgets demo shows 27 FPS, but with lvgl-8.3.4, it 's 200 FPS, what reason will cause this change?
thanks.

**Comment by kisvegabor** [comment]
Looks good, thank you! 

> with lvgl-master, the widgets demo shows 27 FPS, but with lvgl-8.3.4, it 's 200 FPS, what reason will cause this change?
thanks.

We have changed how we measure the FPS. Earlier it was calculated from the pure rendering time (which can be really high). In `master` it's measures the time between two calls of render timer. Will adding this show higher FPS?
```
  lv_timer_t * timer  =_lv_disp_get_refr_timer(NULL);
  lv_timer_set_period(timer, 10);
```

**Comment by pyway** [comment]
I have changed the value of LV_DEF_REFR_PERIOD from 33 to 5, so lvgl-master demo shows about 200FPS. (38400*2400 screen resolution)

**Comment by kisvegabor** [comment]
Great news! :relaxed: 

> 38400*2400 screen resolution

I guess you meant 3,840x2,400.  :slightly_smiling_face:

**Comment by pyway** [comment]
Yes, it's 3,840x2,400. LVGL does work on PC very well (maybe， some widgets need to expand it's memory or other thing), it's really a great GUI.

**Comment by pyway** [comment]
Yes, it's 3,840x2,400. LVGL does work on PC very well (maybe， some widgets need to expand it's memory or other thing), it's really a great GUI.

**Comment by kisvegabor** [comment]
Happy to hear that! :slightly_smiling_face: 

If all seem work, please close this issue.

**Comment by pyway** [comment]
but if i don't patch this change, the textarea widget does not receive the input of keyboard with lvgl-8.3.x or master branch,
that is my question.

**Comment by kisvegabor** [comment]
Oh I see, I forgot that the original issue was not the FPS display. :slightly_smiling_face: 

I can merge it to `master` and can you send an other PR for `release/v8.3`?

**Pull request closed without merging**
