### PR TITLE
Implement GC9A01 driver

### PR DESCRIPTION
**Pull request by winneymj**
Implement GC9A01 driver for lvgl

### CODE REVIEW

**Review by embeddedt — CHANGES_REQUESTED** [review]
Please ensure that this is a `.c` and not `.cpp` file; at first glance I don't see any major use of C++ features.

**Comment by kisvegabor** [comment]
Looks good to me, thank you!

**Review by embeddedt — COMMENTED** [review]
Maybe I missed something but I don't see where `GC9A01_HOR_RES` and `GC9A01_VER_RES` are defined/expected to be configured.

**Comment by winneymj** [comment]
> GC9A01_HOR_RES

Cleaned up GC9A01_HOR_RES and GC9A01_VER_RES

**Comment by embeddedt** [comment]
Could you add default values to the top of the source file, like was done for the [ST7565 driver](https://github.com/lvgl/lv_drivers/blob/fed54c8d694eb24ff1a3ac78ad42a5840b3bb904/display/ST7565.c#L27-L28)?

**Comment by winneymj** [comment]
> Could you add default values to the top of the source file, like was done for the [ST7565 driver](https://github.com/lvgl/lv_drivers/blob/fed54c8d694eb24ff1a3ac78ad42a5840b3bb904/display/ST7565.c#L27-L28)?

Please take a look

**Comment by winneymj** [comment]
Any more updates needed to this pull request?

**Comment by kisvegabor** [comment]
Sorry for the late replay. It seems good and I merged it.

Thank you for the contribution.

**Pull request merged**
