### PR TITLE
Add some improvements for the new native Windows driver (win32drv)

### PR DESCRIPTION
**Pull request by MouriNaruto**
- Improve the zoomed graphic quality.
- Improve the DPI support.
- Fix out of range issue in the pointer input device driver.
- Add native render support for 16, 8 and 1 LVGL color depth mode.

Before

image

After

image

### CODE REVIEW

**Comment by kisvegabor** [comment]
As far as I can judge it looks good. 

Side note: I didn't know the `MulDiv` functions. What a great name for this common calculation. Probably I'll add something like this in `lv_math.h`. :slightly_smiling_face:

**Comment by MouriNaruto** [comment]
@kisvegabor 

Here is the documentation of 'MulDiv' function.
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-muldiv

The function multiplies two 32-bit values and then divides the 64-bit result by a third 32-bit value. The final result is rounded to the nearest integer. It's a common API used in the High DPI support.

**Comment by kisvegabor** [comment]
Thanks! In LVGL something like this is used to avoid floating-point numbers. E.g. `(10 * 3) / 4`.

**Comment by MouriNaruto** [comment]
@kisvegabor 

> In LVGL something like this is used to avoid floating-point numbers.

But I do some search and don't find the similar API in lv_math.h.

**Comment by kisvegabor** [comment]
>> Probably I'll add something like this in lv_math.h. slightly_smiling_face
 
> But I do some search and don't find the similar API in lv_math.h.


I meant I'll add it in the future. 

Anyway, as the PR looks good, so I merge it.

**Comment by MouriNaruto** [comment]
Thanks for merging.

> I meant I'll add it in the future.

Got it.

**Pull request merged**
